### ISSUE TITLE
Testing: compare module.xml conversion with source html

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/stepmod2mn#36]
Source https://github.com/metanorma/stepmod2mn/issues/25

To do:
- convert `\data\modules\activity\module.xml` into adoc
- generate Metanorma HTML
- compare the visualization with the source document from `\data\modules\activity\sys\*.xml`
- fix the issues in stepmod2mn XSLTs

**Comment by Intelligent2013** [comment]
- [ ] Abstract at begin of the Foreword:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/4101b1a3-aba6-42ee-ae56-8311970475e3)

**Comment by Intelligent2013** [comment]
> Abstract at begin of the Foreword:

Regarding https://www.metanorma.org/author/topics/document-format/sections/#arbitrary-prefatory-clauses:
`In ISO only the “Foreword” is allowed — arbitrarily named preface sections are prohibited, in accordance with ISO Directives Part 2.`

**Comment by ronaldtse** [comment]
@Intelligent2013 where is the "Abstract" needed?

**Comment by Intelligent2013** [comment]
@ronaldtse In the source document, the "Abstract" renders on the cover page (`cover.xml`):
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/9450c347-2620-4d1e-9251-fa3a74bae23f)

Currently, in the Metanorma output, it renders as part of the Foreword.

**Comment by ronaldtse** [comment]
Can you file an issue under the iso-10303-stepmod repository with the title prefix "WG12 issue: ..."? Thanks.

**Comment by Intelligent2013** [comment]
- [ ] no items is `Normative references`
`02-norm-refs.adoc`:
```adoc
[bibliography]
== Normative references

* [[[_010303000001,ISO 10303-1]]], _Industrial automation systems and integration — Product data representation and exchange— Part 1: Overview and fundamental principles_

* [[[_010303000011,ISO 10303-11]]], _Industrial automation systems and integration — Product data representation and exchange— Part 11: Description methods: The EXPRESS language reference manual_

* [[[_010303000041,ISO 10303-41]]], _Industrial automation systems and integration — Product data representation and exchange— Part 41: Integrated generic resource: Fundamentals of product description and support_

* [[[_10303001049,ISO/TS 10303-1049]]], _Industrial automation systems and integration — Product data representation and exchange— Part 1049: Application module: Activity method_
```

but Metanorma presentation XML is empty:
```xml
<references id="_normative_references" normative="true" obligation="informative" displayorder="5">
	<title depth="1">2<tab/>Normative references</title>
	<p id="_21971d30-bb88-56a2-0d5b-aca5e0104f76">There are no normative references in this document.</p>
</references>
```

**Comment by Intelligent2013** [comment]
> no items in `Normative references`

id should be started with letter. Fixed. 
```
* [[[bibitem_010303000001,ISO 10303-1]]],
```

**Comment by Intelligent2013** [comment]
- [ ] wrong Terms section hierarchy
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/7c42a9cb-ac3f-4a5a-ada0-a97e961d55c8)
Original HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/56536f10-25ea-4380-b0dd-8a8f34e7efb1)

**Comment by Intelligent2013** [comment]
- [ ] in the section 4.1.
`USE FROM Activity_method_arm   -- ;ISO/TS 10303-1049`
Original HTML:
`USE FROM [Activity_method_arm](file:///D:/Work/Metanorma/Stepmod/iso-10303-stepmod-master/data/modules/activity_method/sys/4_info_reqs.xml#activity_method_arm);   --  ISO/TS 10303-1049`

- [ ] note and example markup isn't working (https://github.com/metanorma/stepmod2mn/issues/24):
`(*”Activity_arm.__note” The schemas referenced above are specified in the following part of ISO 10303: *)`
Original HTML:
`NOTE 1  The schemas referenced above are specified in the followingpart of ISO 10303:`
May be the reason in the command `bundle exec metanorma -t iso -x presentation,html document.adoc`, and should be use `bundle exec metanorma collection collection.yml -x xml,html,presentation -w iso10303-41`,,,

**Comment by Intelligent2013** [comment]
- [ ] multiple figures references
`See Annex C, Figure C.1 and Figure C.2 for a graphical representation of this schema.`

Original HTML:
`NOTE 2  See Annex C, Figures C.1 and C.2 for a graphical representation of this schema.`

**Comment by Intelligent2013** [comment]
- [ ] Hyperlink are missing
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/e1441ad3-5dbb-42e2-9387-46494457daff)

Original HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/bc1ed427-0397-45f8-93e4-95dcb9d1bdda)

**Comment by Intelligent2013** [comment]
> Hyperlink are missing

In adoc there are express references like `<<express:Activity_method>>`:
`An *Activity* is the identification of the occurrence of an action that has taken place, is taking place, or is expected to take place in the future. The procedure executed during that *Activity* is identified with the <<express:Activity_method>> that is referred to by the *chosen_method* attribute. 
`

**Comment by Intelligent2013** [comment]
- [ ] text in asterisks instead of bold (section 5)
`*Title:* The clause title contains:`
`*Source:* This section contains:`

**Comment by Intelligent2013** [comment]
- [ ] less sign missing in Metanorma HTML
adoc:
```adoc
<>:: enclosed section constrains at one or more required
      reference path;
```
Metanorma presentation XML - ok:
```xml
<dt>&#x3c;&#x3e;</dt>
          <dd>
            <p id="_">enclosed section constrains at one or more required
reference path;</p>
          </dd>
```
Metanorma HTML - not ok, `&#x3c` is missing:
```xml
<dt><p>&#x3e;</p></dt><dd><p id="_92108d98-dd0f-8df0-87a8-dca240aaec4a">enclosed section constrains at one or more required
reference path;</p>
</dd>
```

**Comment by Intelligent2013** [comment]
- [ ] characters replacement should be disabled

Metanorma HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/74251d44-dc8d-431c-a0c9-5f42a4c61ca3)

original HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/03c68d68-0749-48ec-937a-d1a60295afcb)

**Comment by Intelligent2013** [comment]
- [ ] section 5.1 text difference - `are` vs. `is` and `/MAPPING_OF/`:
Metanorma HTML:
`The definition and use of mapping templates are not supported in the present version of the application modules. However, use of predefined templates /MAPPING_OF/, /SUBTYPE/, and /SUPERTYPE/ is supported.
`
Original HTML:
`The definition and use of mapping templates is not supported in the present version of the application modules. However, use of predefined templates /SUBTYPE/ and /SUPERTYPE/ is supported.
`

**Comment by Intelligent2013** [comment]
- [ ] another elements order
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/00075717-6141-4564-85e4-01a14fa2d58c)

Original HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/26358552-7bdd-4c5f-b6b0-64a51cfd8e2e)

- [ ] sections number in adoc, for instance:
```
5.1.1.1 <<activity_arm.activity.description,description>>
```

**Comment by Intelligent2013** [comment]
- [ ] wrong Table E.1 structure
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/094d5305-bb18-4cb3-9dbe-f360dc2a892f)

Original HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/57045753-93e9-445a-b284-0176204356da)

**Comment by Intelligent2013** [comment]
- [ ] Index differences
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/4b950f77-ae0c-4f76-8852-54e53d34a3d3)

Original HTML:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/f5df14b8-f528-43cd-a3e5-fa70f635e0a1)

**Comment by Intelligent2013** [comment]
- [ ] `Activity` is missing in Index:
![image](https://github.com/metanorma/stepmod2mn/assets/5559926/2fb0ceb5-cf2d-4277-bf86-2b1ba95012b3)
Issue added: https://github.com/metanorma/metanorma/issues/298

**Comment by Intelligent2013** [comment]
Currently issues:
- [ ] note and example markup isn't working (https://github.com/metanorma/stepmod2mn/issues/36#issuecomment-1567361590)
- [ ] Hyperlinks are missing (https://github.com/metanorma/stepmod2mn/issues/36#issuecomment-1567400962)
- [ ] less sign missing in Metanorma HTML (https://github.com/metanorma/stepmod2mn/issues/36#issuecomment-1568209178)
- [ ] characters replacement should be disabled (https://github.com/metanorma/stepmod2mn/issues/36#issuecomment-1568230695)
- [ ] `Activity` is missing in Index (https://github.com/metanorma/stepmod2mn/issues/36#issuecomment-1570008669)

**Comment by Intelligent2013** [comment]
> - [ ] characters replacement should be disabled
> 
> Metanorma HTML:
> ![image](https://github.com/metanorma/stepmod2mn/assets/5559926/74251d44-dc8d-431c-a0c9-5f42a4c61ca3)
> 
> original HTML:
> ![image](https://github.com/metanorma/stepmod2mn/assets/5559926/03c68d68-0749-48ec-937a-d1a60295afcb)

The solution is
```
pass-format:all[--]:: the text following is a comment or introduces a clause reference;
```

**Comment by ronaldtse** [comment]
> > * [ ]  characters replacement should be disabled
> ```
> pass-format:all[--]:: the text following is a comment or introduces a clause reference;
> ```

Sorry, why do we want to disable the `--`?

**Comment by ronaldtse** [comment]
> * [x]  section 5.1 text difference - `are` vs. `is` and `/MAPPING_OF/`:
>   Metanorma HTML:
>   `The definition and use of mapping templates are not supported in the present version of the application modules. However, use of predefined templates /MAPPING_OF/, /SUBTYPE/, and /SUPERTYPE/ is supported. `
>   Original HTML:
>   `The definition and use of mapping templates is not supported in the present version of the application modules. However, use of predefined templates /SUBTYPE/ and /SUPERTYPE/ is supported. `

@Intelligent2013 The content of the source (we're on the `develop` branch) is not exactly the same as SMRLv8. We now have SMRLv9 to compare against, which is still different from `develop`.

**Comment by Intelligent2013** [comment]
> > > * [ ]   characters replacement should be disabled
> > 
> > 
> > ```
> > pass-format:all[--]:: the text following is a comment or introduces a clause reference;
> > ```
> 
> Sorry, why do we want to disable the `--`?


The original HTML:
> ![image](https://github.com/metanorma/stepmod2mn/assets/5559926/03c68d68-0749-48ec-937a-d1a60295afcb)

Metanorma converts the double hyphen-minus `--` (0X0D) to the sequence `thin space` `em dash` `thin space` (0x2009 0x2014 0x2009), therefore we need to escape it in `pass-format`.

**Comment by Intelligent2013** [comment]
No more actionable after updates in https://github.com/metanorma/stepmod2mn/issues/159.
